CREATE OR ALTER PROC P_BUSCAR_ALL_AFILIADO
AS
BEGIN 
SELECT * FROM AFILIADO
END;

go
		CREATE OR ALTER PROCEDURE P_BUSCAR_AFILIADO (@NOMBRE VARCHAR(50), @APELLIDO VARCHAR(50) , @CEDULA VARCHAR(50))									
		AS

		BEGIN 
		SELECT A.ID,
				A.NOMBRE,
				A.APELLIDO,
				A.CEDULA,
				A.FECHA_NACIMIENTO,
				A.SEXO,
				A.NUMERO_SEGURIDAD_SOCIAL,
				A.FECHA_REGISTRO,
				A.ID_ESTATUS,
				P.PLANS ,
				A.MONTO_CONSUMIDO,
				P.MONTO_COBERTURA,
				(P.MONTO_COBERTURA - A.MONTO_CONSUMIDO ) 
				AS MONTO_RESTANTE FROM AFILIADO A, PLANES P WHERE NOMBRE = @NOMBRE OR APELLIDO = @APELLIDO OR CEDULA = @CEDULA
		AND P.ID = A.ID_PLAN
   
		END;
		go;


		--AGREGAR
CREATE OR ALTER PROCEDURE P_INSERT_AFILIADO (@NOMBRE VARCHAR(50), @APELLIDO VARCHAR(50) , @FECHA_NACIMIENTO DATETIME,
@SEXO VARCHAR(1), @CEDULA VARCHAR(50), @NUMERO_SEGURIDAD_SOCIAL VARCHAR(50), @FECHA_REGISTRO DATETIME, 
@MONTO_CONSUMIDO DECIMAL, @ID_ESTATUS INT, @ID_PLAN INT)									

AS

BEGIN 
INSERT INTO [dbo].[AFILIADO]
           ([NOMBRE]
           ,[APELLIDO]
           ,[FECHA_NACIMIENTO]
           ,[SEXO]
           ,[CEDULA]
           ,[NUMERO_SEGURIDAD_SOCIAL]
           ,[FECHA_REGISTRO]
           ,[MONTO_CONSUMIDO]
           ,[ID_ESTATUS]
           ,[ID_PLAN])
     VALUES
           (@NOMBRE,
		   @APELLIDO,
		   @FECHA_NACIMIENTO,
		   @SEXO,
		   @CEDULA,
		   @NUMERO_SEGURIDAD_SOCIAL,
		   @FECHA_REGISTRO,
		   @MONTO_CONSUMIDO,
		   @ID_ESTATUS,@ID_PLAN)


END;


SELECT * FROM AFILIADO
go

CREATE OR ALTER PROC P_BUSCAR_ALL_AFILIADO
AS
BEGIN 
SELECT * FROM AFILIADO
END;




Create database AFILIADOS_ERNESTO_CANDIDATO
go
USE AFILIADOS_ERNESTO_CANDIDATO


CREATE TABLE AFILIADO
(
ID INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO VARCHAR(50) NOT NULL,
FECHA_NACIMIENTO DATETIME NOT NULL,
SEXO VARCHAR(1),
CEDULA VARCHAR(50) NOT NULL,
NUMERO_SEGURIDAD_SOCIAL VARCHAR(50),
FECHA_REGISTRO DATETIME DEFAULT GETDATE(),
MONTO_CONSUMIDO DECIMAL(20,2),
ID_ESTATUS INT FOREIGN  KEY REFERENCES ESTATUS(ID),
ID_PLAN INT FOREIGN  KEY REFERENCES PLANES(ID),

); 


CREATE TABLE ESTATUS 
(
ID INT IDENTITY PRIMARY KEY,
ESTATUS VARCHAR(8) NOT NULL,
);


CREATE TABLE PLANES 
(
ID INT PRIMARY KEY IDENTITY(1,1),
PLANS VARCHAR(50) NOT NULL,
MONTO_COBERTURA DECIMAL(20,2) NOT NULL,
FECHA_REGISTRO DATETIME DEFAULT GETDATE(),
ID_ESTATUS INT FOREIGN KEY REFERENCES ESTATUS(ID)
);



GO

INSERT INTO [dbo].[AFILIADO]
           ([NOMBRE]
           ,[APELLIDO]
           ,[FECHA_NACIMIENTO]
           ,[SEXO]
           ,[CEDULA]
           ,[NUMERO_SEGURIDAD_SOCIAL]
           ,[MONTO_CONSUMIDO]
           ,[ID_ESTATUS]
           ,[ID_PLAN])
     VALUES
           ('GUSTAVO'
           ,'SANCHEZ'
           ,'11/11/1999'
           ,'M'
           ,'40215079266'
           ,'40215079266'
           ,451
           ,1
           ,2)
GO


		CREATE OR ALTER PROCEDURE P_BUSCAR_AFILIADO (@NOMBRE VARCHAR(50), @APELLIDO VARCHAR(50) , @CEDULA VARCHAR(50))									
		AS

		BEGIN 
		SELECT A.ID,
				A.NOMBRE,
				A.APELLIDO,
				A.SEXO,
				A.CEDULA,A.FECHA_NACIMIENTO,
				A.FECHA_REGISTRO,
				A.NUMERO_SEGURIDAD_SOCIAL,
				A.ID_ESTATUS,
				P.PLANS ,
				A.MONTO_CONSUMIDO,
				P.MONTO_COBERTURA,
				(P.MONTO_COBERTURA - A.MONTO_CONSUMIDO ) 
				AS MONTO_RESTANTE FROM AFILIADO A, PLANES P WHERE NOMBRE = @NOMBRE OR APELLIDO = @APELLIDO OR CEDULA = @CEDULA OR @CEDULA = NULL
				OR @NOMBRE = NULL OR @APELLIDO = NULL OR @NOMBRE = 'undefined' or @APELLIDO = 'undefined' or @CEDULA = 'undefined'
		AND P.ID = A.ID_PLAN
   
		END;
		go;

--AGREGAR
CREATE OR ALTER PROCEDURE P_INSERT_AFILIADO (@NOMBRE VARCHAR(50), @APELLIDO VARCHAR(50) , @FECHA_NACIMIENTO DATETIME,
@SEXO VARCHAR(1), @CEDULA VARCHAR(50), @NUMERO_SEGURIDAD_SOCIAL VARCHAR(50), @FECHA_REGISTRO DATETIME, 
@MONTO_CONSUMIDO DECIMAL, @ID_ESTATUS INT, @ID_PLAN INT)									

AS

BEGIN 
INSERT INTO [dbo].[AFILIADO]
           ([NOMBRE]
           ,[APELLIDO]
           ,[FECHA_NACIMIENTO]
           ,[SEXO]
           ,[CEDULA]
           ,[NUMERO_SEGURIDAD_SOCIAL]
           ,[FECHA_REGISTRO]
           ,[MONTO_CONSUMIDO]
           ,[ID_ESTATUS]
           ,[ID_PLAN])
     VALUES
           (@NOMBRE,
		   @APELLIDO,
		   @FECHA_NACIMIENTO,
		   @SEXO,
		   @CEDULA,
		   @NUMERO_SEGURIDAD_SOCIAL,
		   @FECHA_REGISTRO,
		   @MONTO_CONSUMIDO,
		   @ID_ESTATUS,@ID_PLAN)


END;

go


USE [AFILIADOS_ERNESTO_CANDIDATO]
GO

INSERT INTO [dbo].[AFILIADO]
           ([NOMBRE]
           ,[APELLIDO]
           ,[FECHA_NACIMIENTO]
           ,[SEXO]
           ,[CEDULA]
           ,[NUMERO_SEGURIDAD_SOCIAL]
           ,[MONTO_CONSUMIDO]
           ,[ID_ESTATUS]
           ,[ID_PLAN])
     VALUES
           ('GUSTAVO'
           ,'SANCHEZ'
           ,'11/11/1999'
           ,'M'
           ,'40215079266'
           ,'40215079266'
           ,451
           ,1
           ,2)
GO


		--INACTIVAR
CREATE OR ALTER PROCEDURE P_INACTIVAR_AFILIADO (@ID INT)									

AS

BEGIN 
UPDATE [dbo].[AFILIADO]
    SET
           [ID_ESTATUS] = 4
     
        WHERE
    ID = @ID

END;

go

		--INACTIVAR
CREATE OR ALTER PROCEDURE P_RESTAR_MONTO_AFILIADO (@ID INT, @MONTO_CONSUMIDO DECIMAL)									

AS

BEGIN 
UPDATE [dbo].[AFILIADO]
    SET
           
           [MONTO_CONSUMIDO] = MONTO_CONSUMIDO + @MONTO_CONSUMIDO
     
        WHERE
    ID = @ID

END;



update AFILIADO set ID_ESTATUS = 1 


	go	--AGREGAR
CREATE OR ALTER PROCEDURE P_ACTUALIZAR_AFILIADO (@ID INT,@NOMBRE VARCHAR(50), @APELLIDO VARCHAR(50) , @FECHA_NACIMIENTO DATETIME,
@SEXO VARCHAR(1), @CEDULA VARCHAR(50), @NUMERO_SEGURIDAD_SOCIAL VARCHAR(50), @FECHA_REGISTRO DATETIME, 
@MONTO_CONSUMIDO DECIMAL, @ID_ESTATUS INT, @ID_PLAN INT)									

AS

BEGIN 
UPDATE [dbo].[AFILIADO]
    SET
           [NOMBRE] = @NOMBRE,
           [APELLIDO] = @APELLIDO,
           [FECHA_NACIMIENTO] = @ID_PLAN,
           [SEXO] = @SEXO,
           [CEDULA] = @CEDULA,
           [NUMERO_SEGURIDAD_SOCIAL] = @NUMERO_SEGURIDAD_SOCIAL,
           [FECHA_REGISTRO] = @FECHA_REGISTRO,
           [MONTO_CONSUMIDO] = @MONTO_CONSUMIDO,
           [ID_ESTATUS] = @ID_ESTATUS,
           [ID_PLAN] = @ID_PLAN
        WHERE
    ID = @ID

END;



